server:
  port: 8086
 
spring:
  application:
    name: NOTIFICATION-SERVICE 
    
eureka:
  instance:
#    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    
    

      