server:
  port: 8085
 
spring:
  application:
    name: PROJECT-SERVICE 
    
eureka:
  instance:
#    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
      