apiVersion: v1
kind: Service
metadata:
    name: pmsdb
    labels:
        name: pmsdb-service
        app: pms-app
spec:
    ports:
    - port: 5432
      targetPort: 5432
    selector:
        name: postgres-pod
        app: pms-app